# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20180319_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='link',
            field=models.URLField(default='www.facebook.com'),
            preserve_default=False,
        ),
    ]
