# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_estate_raw_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='raw_text',
            field=models.TextField(),
        ),
    ]
