# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20180319_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='source',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
