# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_estate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='location',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
