# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_estate_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NestiaEstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('nestiaId', models.CharField(max_length=200)),
                ('propertyLeaseId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('block', models.CharField(max_length=200)),
                ('propertyTypeName', models.CharField(max_length=200)),
                ('propertyTypeCode', models.CharField(max_length=200)),
                ('rentalTypeName', models.CharField(max_length=200)),
                ('rentalTypeCode', models.CharField(max_length=200)),
                ('bedroomNumberName', models.CharField(max_length=200)),
                ('bedroomNumberCode', models.CharField(max_length=200)),
                ('bathroomNumberName', models.CharField(max_length=200)),
                ('bathroomNumberCode', models.CharField(max_length=200)),
                ('roomTypeName', models.CharField(max_length=200)),
                ('roomTypeCode', models.CharField(max_length=200)),
                ('bathroomTypeName', models.CharField(max_length=200)),
                ('bathroomTypeCode', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('ImageURL1', models.URLField()),
                ('ImageURL2', models.URLField()),
                ('ImageURL3', models.URLField()),
                ('ImageURL4', models.URLField()),
                ('ImageURL5', models.URLField()),
                ('isLike', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('subDistrictId', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('projectId', models.CharField(max_length=200)),
                ('isRecommendAgent', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('ask_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
