# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_nestiaestate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestiaestate',
            name='nestiaId',
        ),
    ]
