# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_remove_nestiaestate_nestiaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nestiaestate',
            name='nestiaId',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
